############################
# --- Required options --- #
############################

title: Tess Bembo – Quantitative Finance & Data Science

author: Tess Bembo

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  Blog: "blog"
  Contact: "contact"

################
# --- Logo --- #
################

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "tessbembo@gmail.com"
  github: TessBembo
  linkedin: tess-bembo

rss-description: A portfolio and blog documenting my work in quantitative finance, data science, and modeling.

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: true
  reddit: false

url-pretty: "tessbembo.github.io"

title-on-all-pages: true

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

post_search: true
edit_page_button: true
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

page-col: "#fff9fb"            # soft pinkish white
text-col: "#333333"            # dark gray for text
link-col: "#e75480"            # pink links
hover-col: "#d64570"           # deeper pink on hover
navbar-col: "#ffe6ef"          # very light pink navbar
navbar-text-col: "#333333"
navbar-border-col: "#ffccd5"   # subtle pink border
footer-col: "#ffe6ef"
footer-text-col: "#555555"
footer-link-col: "#e75480"
footer-hover-col: "#d64570"

# Optional background images (leave commented if not using)
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers
#mobile-theme-col: "#e75480"

# Include custom CSS to force pink theme
site-css:
  - "/assets/css/custom-colors.css"

#################################
# --- Web Analytics Section --- #
#################################

#gtag: "G-XXXXXXXXXX"
#cloudflare_analytics: ""
#gtm: ""

####################
# --- Comments --- #
####################

#disqus: ""
#fb_comment_id: ""
#commentbox: "" 
#giscus:
#  hostname: giscus.app
#  repository: 
#  repository-id:
#  category: Announcements
#  category-id:
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189


