############################
# --- Required options --- #
############################

title: Tess Bembo – bridging psychology and mathematics
author: Tess Bembo
remote_theme: daattali/beautiful-jekyll

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Projects: "blog"
  Curriculum Vitae: "curriculum-vitae"

################
# --- Logo --- #
################

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "tessbembo@gmail.com"
  github: TessBembo
  linkedin: tess-bembo

rss-description: A portfolio and blog documenting my personal projects in mathematics and psychology.

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: true
  reddit: false

url-pretty: "tessbembo.github.io"

title-on-all-pages: true

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

post_search: true
edit_page_button: true
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

page-col: "#fff9fb"
text-col: "#333333"
link-col: "#e75480"
hover-col: "#d64570"
navbar-col: "#ffe6ef"
navbar-text-col: "#333333"
navbar-border-col: "#ffccd5"
footer-col: "#ffe6ef"
footer-text-col: "#555555"
footer-link-col: "#e75480"
footer-hover-col: "#d64570"

# Optional background images
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Mobile browser theme color
#mobile-theme-col: "#e75480"

# Custom CSS
site-css:
  - "/assets/css/custom-colors.css"

#################################
# --- Web Analytics Section --- #
#################################

#gtag: "G-XXXXXXXXXX"

####################
# --- Comments --- #
####################

# To enable a comment system, uncomment one:
#disqus: ""
#commentbox: ""
#giscus:
#  repository: ""
#  category: ""
#  mapping: pathname

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

collections:
  projects:
    output: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap

